# Generated by Django 4.2.7 on 2026-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('record_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('normalized_record_id', models.CharField(db_index=True, max_length=50)),
                ('location_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('event_date', models.CharField(blank=True, default='', max_length=50)),
                ('category_code', models.CharField(blank=True, default='', max_length=50)),
                ('actor_id', models.CharField(blank=True, default='', max_length=50)),
                ('base_value_raw', models.CharField(blank=True, default='', max_length=100)),
                ('adjustment_raw', models.CharField(blank=True, default='', max_length=100)),
                ('total_value_raw', models.CharField(blank=True, default='', max_length=100)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('entry_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('record_ref_raw', models.CharField(blank=True, default='', max_length=100)),
                ('normalized_record_ref', models.CharField(db_index=True, max_length=50)),
                ('location_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('recorded_on', models.CharField(blank=True, default='', max_length=50)),
                ('value_raw', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
